### ISSUE TITLE
Update loading screen to show all services status.

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery#455]
Need to update initial load screen to show list of services and their status.

Create new welcome experience:

- [x] a list of all the services being loaded, a progress timings for each service, and status colours, an idea of how long each service would take
- [x] a series of tabs that provide documentation
- [x] if first time and services are loaded show ready to roll page
- [ ] if not first time and services are load jump to app

Tabs
- [x] welcome first, explain service install and have a button to jump to services.
- [x] welcome normal, notmal 
- [x] intro, small intro from website
- [ ] services, table with timing and status
- [x] documentation, iframe of our site.
- [x] Read to Roll, jump to the app

Opportunities
- [ ] potentially a write to disk benchmark the we run at the beginning that will scale the time for us

**Comment by brettforbes** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/24556510/229433808-46f751ab-b055-47e2-94c4-167894a65555.png">

**Comment by wildone** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/170312/229708915-f56974a8-3f35-4c71-8b8b-a737ed49cf29.png">

**Comment by Harikarthyk** [comment]
![image](https://user-images.githubusercontent.com/54505967/229709083-00aea38d-f35d-4375-8564-fc65edbbb084.png)

**Comment by brettforbes** [comment]
I like the purple thing, but we should add::
- a list of all the services being loaded
- a progress bar for each service, and status colours
- an idea of how long each service would take
- potentially a write to disk benchmark the we run at the beginning that will scale the time for us
- a series of tabs that provide documentation

**Comment by wildone** [comment]
this is done.
