### ISSUE TITLE
Infinite app loader running

### ISSUE THREAD

**Issue by sanjayaapna** [typerefinery-ai/typerefinery#460]
Followed the steps:

- take the "Develop" branch's latest pull
- execute the command "npm run electron:clean"
- execute the command "npm run electron:start"

infinite loader running
![image](https://user-images.githubusercontent.com/96102060/230061052-d51d8875-8a77-40c9-a4e7-a797bc9c9a9a.png)

As per the terminal error showing as below:
![image](https://user-images.githubusercontent.com/96102060/230060937-459d82b6-2296-43af-91b4-07337ea0807f.png)

**Comment by Rahul139-stack** [comment]
Resolved
