### ISSUE TITLE
Investigate a way to bubble out modal events into parent page from within iframe.

### ISSUE THREAD

**Issue by wildone** [typerefinery-ai/typerefinery#467]
Would be easier for user to have more space in modal if it appears in parent pages.

Can we find a generic way to bubble up events to parent frame.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/170312/231078999-11344320-1059-488d-bc8d-530ba2e1b039.png">

**Comment by Harikarthyk** [comment]
Completed
