### ISSUE TITLE
Mongo Service not getting stop

### ISSUE THREAD

**Issue by sanjayaapna** [typerefinery-ai/typerefinery#475]
# Steps to re-produce

- [ ] clean the existing configuration using "npm run electron:clean"
- [ ] Start the services using the "npm run servicesdebug"
- [ ] Start the "Mongo" service via GUI
- [ ] When I tried to stop the service using the "STOP" button, it threw an error

![image](https://user-images.githubusercontent.com/96102060/234210309-e4ba6b4b-90e8-48c1-8242-f2cc175743c2.png)

![image](https://user-images.githubusercontent.com/96102060/234209424-3efd5f06-a4ed-49a9-bf4a-3068c4a8d926.png)

![image](https://user-images.githubusercontent.com/96102060/234209593-694d3312-fd25-4207-9925-cab45da130f1.png)

- [ ] I'm reporting this issue for the "Develop" branch.

# Expected Behavior
It should stop the "Mongo" service and it should kill the running process as well

# Current Behavior

- Initially, the service start working as expected
- Further, if we want to stop/ start the service then it throws an error
- I tried to stop/ start the service because CMS/ BMP server log showed a MongoDB authentication error
- To start the service again from GUI, I have to manually kill the running Mongo service from "Task Manager"
![image](https://user-images.githubusercontent.com/96102060/234212597-656a5845-b689-4ea4-9c0a-fec8ead5d4e8.png)

**Comment by wildone** [comment]
Here is the result of my test on develop branch.

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/170312/235387184-1e8398fd-0ac7-4624-8627-f5b9c727c187.png">

**Comment by sanjayaapna** [comment]
It seems working fine with the latest Develop branch. I tried to stop and start it from the GUI

![image](https://user-images.githubusercontent.com/96102060/235433103-142d5129-798a-4332-b3b5-b7d7d33c32ac.png)
