### ISSUE TITLE
In new build, services were not starting.

### ISSUE THREAD

**Issue by Shivam-apna** [typerefinery-ai/typerefinery#478]
- Created a new build from develop by doing ``` npm run electron:clean ``` then ``` npm run app:build ```.
- By running ``` npm run electron:start ```it is working fine.
- After installing the app it stops on loading screen as tms and flow services were showing stoped.

**Comment by Rahul139-stack** [comment]
Hi team,Taken latest pull from develop branch.
Totaljs and TMS services remains in Stopped status .
![image](https://user-images.githubusercontent.com/81350384/235410336-384df3b0-895f-4b82-acac-4608272e2f28.png)

**Comment by Harikarthyk** [comment]
+ 1

When I run the command npm run electron:start, all the things are working good.
When I take a build few services are getting stopped.

**Comment by wildone** [comment]
have you tried this from latest develop?

**Comment by wildone** [comment]
same as #464
