### ISSUE TITLE
CMS tab experience not able to load the url 

### ISSUE THREAD

**Issue by Rahul139-stack** [typerefinery-ai/typerefinery#481]
Cms tab experience not able to load the url in iframe

- set X-Frame-Options header for all responses on CMS so that I can load CMS UI in an iFrame.
- 
![image](https://user-images.githubusercontent.com/81350384/235423945-625d1091-93f0-45a1-b5eb-4b55201bec41.png)

Reference:https://github.com/websight-io/starter/issues/155

**Comment by wildone** [comment]
I have added this https://github.com/typerefinery-ai/typerefinery/commit/7db03ae534e9d83145cf6c1587cfb60f6d03e5a9
And have done this on CMS side as well https://github.com/typerefinery-ai/typerefinery-websight/commit/dd252775bc260fd5e9c7df796724f12ffb92b48b

**Comment by wildone** [comment]
@Rahul139-stack please test when new version is release.

**Comment by Rahul139-stack** [comment]
Sure @wildone

**Comment by Rahul139-stack** [comment]
Followed by ticket #487
