### ISSUE TITLE
Make a Generic Python Block

### ISSUE THREAD

**Issue by brettforbes** [typerefinery-ai/typerefinery#529]
The current Python block "Run (Nodes and Edges)" relies on a valid connection and query block as inputs, yet new connection blocks cannot be defined to new databases without knowing the internal id of the new global connection.

A generic Python block would be far more useful and appears relatively simple

# The Generic Python Block
The generic python block adds two new property fields to the configure pane:
1. Inputs field, where one or more dynamic, lower case input names are inputted separated by spaces
2. Outputs field, where one or more dynamic, lower case output names are inputted separated by spaces

The generic python block has brief instructions on:
a. how to identify which python function is run when the script is run
b. how to address input data as parameters in the starting python function
c. how to send the python script outputs to the block outputs (Write jsons, return objects etc?)

This seems like a relatively small task. I have tried it, but my JS skills were too rubbish, and some of the variables and passing approaches are not clear.

**Comment by brettforbes** [comment]
It may be that there is a simpler way. I was almost able to complete this idea, but buggered it up through a lack of knowledge.

Since i have more time (i.e. I can do this full time) perhaps a quick session answering some questions could enable me to execute the block design correctly. I did have it about 80%-ish correct.

So an option, is to spend some short time with me, and then get me to build the block

**Comment by wildone** [comment]
done
